# Generated by Django 5.0.4 on 2024-04-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredDoor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=200, null=True)),
                ('door_number', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date security credentials were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date sub-product updated')),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=200, null=True, verbose_name='RFID card holder name')),
                ('card_uid', models.CharField(max_length=200, null=True, verbose_name='RFID card unique identifier')),
                ('user_qr_code', models.ImageField(null=True, upload_to='user_qr_codes/', verbose_name='Security QR code')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date security credentials were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date sub-product updated')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, null=True)),
                ('entry_img', models.ImageField(null=True, upload_to='entry_img/')),
                ('entry_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date and time at which staff entered the room')),
                ('exit_img', models.ImageField(null=True, upload_to='exit_img/')),
                ('exit_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date and time at which staff exited the room')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date security credentials were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date sub-product updated')),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.secureddoor')),
                ('access_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='security.usersecuritycredential')),
            ],
        ),
        migrations.AddField(
            model_name='secureddoor',
            name='permitted_users',
            field=models.ManyToManyField(related_name='permitted_user_list', to='security.usersecuritycredential'),
        ),
    ]
