# Generated by Django 5.0.4 on 2024-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='entry_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='entry_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='exit_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersecuritycredential',
            name='user_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='user_qr_codes/', verbose_name='Security QR code'),
        ),
    ]
