# Generated by Django 5.0.4 on 2024-04-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securitylog_entry_status_alter_securitylog_entry_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='exit_at',
            field=models.DateTimeField(blank=True, help_text='format: Y-m-d H:M:S', null=True, verbose_name='date and time at which staff exited the room'),
        ),
    ]
