# Generated by Django 5.0.4 on 2024-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_securitylog_exit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureddoor',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='permitted_user_list', to='security.usersecuritycredential'),
        ),
    ]
